In [1]:
#python zip explain
l1=[1,2,3]
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [2]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
 
start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print(result[0:10])
print("Python list addition time:", end - start)
 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Python list addition time: 0.06743192672729492


In [3]:
import numpy as np
import time

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)
 
start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print(result[0:10])
print("NumPy array addition time:", end - start)

[ 0  2  4  6  8 10 12 14 16 18]
NumPy array addition time: 0.014601707458496094


In [4]:
#
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
# same no.of elements in rows
arr=np.array([[1,2,3],[4,5,6]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
#shape- (rows,columns)
arr.shape

(2, 3)

In [9]:
#memory efficiency
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [10]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
 
start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()
print(list_squares[0:10])
print("Python list square time:", end - start)

# NumPy array
arr1 = np.array(list1)

start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print(numpy_squares[0:10])
print("NumPy array square time:", end - start)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Python list square time: 0.07323026657104492
[ 0  1  4  9 16 25 36 49 64 81]
NumPy array square time: 0.0026099681854248047
