In [1]:
import numpy as np

In [2]:
!pip install numpy

Active code page: 1252
Defaulting to user installation because normal site-packages is not writeable


In [3]:
arr1=np.array([1,2,3,4])     #1-D ARRAY
arr2=np.array([[1,2,3],[4,5,6]])  #2-D

In [4]:
arr1


array([1, 2, 3, 4])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [9]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(1,100,10)  # till 100-1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [12]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [13]:
myarr.shape #(r,c)

(4, 3)

In [14]:
myarr.size #total elements

12

In [15]:
myarr.ndim #dimension

2

In [16]:
myarr.dtype

dtype('int64')

In [17]:
# CONVERT DATATYPE

In [18]:
#EXPLICIT
arr = np.array([1, 2, 3], dtype=np.float32)
arr

array([1., 2., 3.], dtype=float32)

In [19]:
#implicit
arr_int = arr.astype(np.int32)
arr_int

array([1, 2, 3], dtype=int32)

In [20]:
#reshape()
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [21]:
re=arr.reshape((3,2))
re

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#flatten()
flat=arr.flatten()
flat

array([1, 2, 3, 4, 5, 6])