In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [2]:
flat=arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [3]:
flat[0]

np.int64(1)

In [4]:
flat[3:6]

array([4, 5, 6])

In [5]:
flat[:4]  #first elements

array([1, 2, 3, 4])

In [6]:
flat[4:] #last elements

array([ 5,  6,  7,  8,  9, 11, 12, 13])

In [7]:
flat[::2]  #every second element

array([ 1,  3,  5,  7,  9, 12])

In [8]:
#sliceing is a view not a copy. 
#change affect original

flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
b=flat[3:6]
b

array([4, 5, 6])

In [10]:
b[0]=4444
b

array([4444,    5,    6])

In [11]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [12]:
#not a slice as we use cpoy method
c=flat[3:6].copy()
c

array([4444,    5,    6])

In [13]:
c[1]=3333
c

array([4444, 3333,    6])

In [14]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [15]:
#fancy indexing
arr=np.array([11,22,33,44,55,66,77,88])
arr[[1,3,6]]

array([22, 44, 77])

In [16]:
#boolean masking
arr[arr>40]

array([44, 55, 66, 77, 88])

In [17]:
#EXERCISES

In [18]:
#Create a 3×3 array filled with random numbers and print its shape.
arr=np.array([[11,22,33],[44,55,66],[77,88,99]])
arr.shape

(3, 3)

In [19]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr=np.array([1.1, 2.2, 3.3])
arr=arr.astype(np.int32)
arr

array([1, 2, 3], dtype=int32)

In [20]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr=np.array([1,2,3,4,5,6])
arr[[1,3,5]]

array([2, 4, 6])

In [21]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr=np.array([11,22,33,44,55,66,77,88,99])
arr=arr.reshape((3,3))
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [22]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr=np.array([11,22,33,44,55,66,77,88,99])
arr[arr<50]

array([11, 22, 33, 44])