In [1]:
#Multidimensional Indexing and Axis


In [2]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr,axis=0) #all row element participate

array([12, 15, 18])

In [4]:
np.sum(arr,axis=1) #all column element participate

array([ 6, 15, 24])

In [6]:
#indexing
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
# indexing in 3d array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3D[0,1,2]

np.int64(6)

In [10]:
# Get the first row from both sheets
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [13]:
#select data along axis
#Get all rows of the first column
first_col=arr[:,0]
first_col

array([1, 4, 7])

In [14]:
# Get the first row from each "sheet" in a 3D array
first_row=arr3D[:,0,:]
first_row

array([[1, 2, 3],
       [7, 8, 9]])

In [15]:
#changing data along axes
arr3D[:,0,:]=0
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])