In [1]:
#Data Types in NumPy
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype) 

int64


In [2]:
#change datatype
arr.astype("float64")

array([1., 2., 3., 4., 5.])

In [3]:
arr2=np.array([11,22,33,44],dtype="float32")
arr2

array([11., 22., 33., 44.], dtype=float32)

In [4]:
arr2.nbytes

16

In [5]:
arr.nbytes

40

In [6]:
arr.dtype

dtype('int64')

In [7]:
#complex numbers
arr3 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
arr3

array([1.+2.j, 3.+4.j, 5.+6.j])