In [28]:
import numpy as np
arr=np.array([3,4,5,3,6])

In [29]:
np.min(arr)  #minimum

np.int64(3)

In [30]:
np.max(arr)  #maximum

np.int64(6)

In [31]:
np.mean(arr)  #average

np.float64(4.2)

In [32]:
np.std(arr) #standard deviation

np.float64(1.16619037896906)

In [33]:
np.var(arr)  #variance

np.float64(1.3599999999999999)

In [34]:
np.sum(arr)

np.int64(21)

In [35]:
np.prod(arr)

np.int64(1080)

In [36]:
np.median(arr)

np.float64(4.0)

In [37]:
np.percentile(arr,50)

np.float64(4.0)

In [38]:
np.argmin(arr) #index of the minimum value

np.int64(0)

In [39]:
np.argmax(arr) #index of the maximum value

np.int64(4)

In [42]:
np.unique(arr)

array([3, 4, 5, 6])

In [44]:
np.cumsum(arr)

array([ 3,  7, 12, 15, 21])

In [45]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
np.log(arr)

array([1.09861229, 1.38629436, 1.60943791, 1.09861229, 1.79175947])

In [47]:
np.exp(arr)

array([ 20.08553692,  54.59815003, 148.4131591 ,  20.08553692,
       403.42879349])